2020-02-09 01:44:44,224 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-09 12:48:11,797 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-09 12:48:33,272 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-09 12:55:42,956 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-10 22:44:18,204 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-10 22:59:42,019 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-10 23:40:45,745 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-17 00:21:33,884 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-17 00:34:33,633 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-17 00:50:36,794 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-17 00:59:26,889 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-17 01:05:39,942 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-17 01:05:47,287 ERROR: Exception on /user/sheila [GET] [in d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\My Stuff\Projects\2020\Megatutorial\app\routes.py", line 84, in user
    next_url=next_url, prev_url=prev_url)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\jinja2\loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\My Stuff\Projects\2020\Megatutorial\app\templates\user.html", line 33, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-02-17 01:07:19,212 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-17 23:58:11,947 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-18 00:05:12,461 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-18 01:14:17,446 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
2020-02-18 01:17:24,860 ERROR: Exception on /reset_password_request [POST] [in d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\Programs\Anaconda\lib\smtplib.py", line 387, in getreply
    line = self.file.readline(_MAXLINE + 1)
  File "D:\Programs\Anaconda\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\My Stuff\Projects\2020\Megatutorial\app\routes.py", line 164, in reset_password_request
    send_password_reset_email(user)
  File "D:\My Stuff\Projects\2020\Megatutorial\app\email.py", line 20, in send_password_reset_email
    user=user, token=token))
  File "D:\My Stuff\Projects\2020\Megatutorial\app\email.py", line 9, in send_email
    mail.send(msg)
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "d:\my stuff\projects\2020\megatutorial\venv\lib\site-packages\flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "D:\Programs\Anaconda\lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "D:\Programs\Anaconda\lib\smtplib.py", line 338, in connect
    (code, msg) = self.getreply()
  File "D:\Programs\Anaconda\lib\smtplib.py", line 391, in getreply
    + str(e))
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: [WinError 10054] An existing connection was forcibly closed by the remote host
2020-02-18 01:38:04,321 INFO: Microblog startup [in D:\My Stuff\Projects\2020\Megatutorial\app\__init__.py:49]
